### ISSUE TITLE
API key don't work 

### ISSUE THREAD

**Issue by nasyaldnya** [Bridel-Igor/Wallomizer#8]
If the API key is placed, the program closes immediately and does not work until I delete a file  Settings.dat

from %appdata%  > Wallomizer

**Comment by Bridel-Igor** [comment]
Check the latest version of Wallomizer (1.1.0). It changes the way the API Key is stored so it may help.
If it does then report success here.
If it doesn't then I'll need some more info on that issue.

**Comment by nasyaldnya** [comment]
The app no ​​longer closes
But the key still doesn't work 

here is what is inside the file Settings.dat  

`  à“ T e s t                                                                                                                         z U s Y s r B 6 N a M H 5 p 8 I 3 R u 8 9 T t H i U L 5 9 R Q e                                                                                                                                                                                                 `
The key is not real

Ask me if you want more information ☺️

**Comment by Bridel-Igor** [comment]
Ok, so let's go through some troubleshooting steps:
1. Try to regenerate your API Key in your account settings and paste the new key into Wallomizer settings. Make sure to paste just the key itself, without spaces, etc. It should be 32 black dots in that field. Try to access the data you need key to. If this doesn't work proceed to the next step.
2. Open your web browser and paste into address bar next line: `https://wallhaven.cc/api/v1/collections?apikey=`
after this line paste your actual API Key and hit Enter.
If you get `{"error":"Unauthorized"}` or other error message then Wallhaven's API doesn't want to work with your API Key for some reason.
If you get the list of all your collections then something is wrong on app's side. And we will continue the troubleshooting.

**Comment by nasyaldnya** [comment]
The three steps did not work

But the key seemed to be at work  an  user collection But it does not work in search collection 

 here more info

- What Windows version do you use?

Windows 10 Home
21H2

- Do you use 86-bit or 64-bit application version?

64-bit

- Send me whole Settings.dat file. Copy-pasting won't work with binary files.
[

](https://mega.nz/file/doFxyKTI#aC4d-Qu9zMLzbP4IoQ2zZOPw2CcPu67f9RgtLj7D9Do)

"The key is not real"

- Does non API Key-related functions work properly?
 yes  

When I add the API Key, all non API Key-related functions stops working in search collection 

Ask me if you want more information

**Comment by Bridel-Igor** [comment]
I checked your Settings.dat file and it appears to be intact.
So it seems that issue is not in the way API key is stored or loaded. 
Also it's confirmed by the fact, that you can use API key in User collections.

My assumption is that something goes wrong in Search collection algorithm during compositing of the URL query to the Wallhaven API, or during parsing stage of API's response. To check those stages I made another pre-release that will write detailed logs during that stages.

So I want you to:
1. [Download](https://github.com/Bridel-Igor/Wallomizer/releases/tag/v1.1.0.2) new pre-release and run it.
2. Enter your real API Key into Wallomizer.
3. Create only one Search collection that will use API Key. Enable only 'NSFW' purity, leave the tag field empty so it will search for all wallpapers.
4. Close the app completely.
5. Run it again.
6. After it starts find in `%AppData%/Roaming/Wallomizer/Logs` file `SearchCollection_loadSettings.log`.
7. Open that file and:
   - If you will see some error messages then report it to me.
   - If there are no errors then grab the last possible URL and paste it into your web browser. Report to me what you see on that web page. Some error message or list of some data.
8. Send me that log file. It will contain your API Key, so you can regenerate it in Wallhaven account settings before sending.

I hope that will be enough to locate the issue, but we will see.

**Comment by nasyaldnya** [comment]
[SearchCollection_loadSettings.log](https://github.com/Bridel-Igor/Wallomizer/files/9128292/SearchCollection_loadSettings.log)

I enter the last possible URL and I see a list of some data.

(({"data":[{"id":"x8rvwo","url":"https:\/\/wallhaven.cc\/w\/x8rvwo","short_url":"https:\/\/whvn.cc\/x8rvwo",))

**Comment by Bridel-Igor** [comment]
Ok. Log tells that URL formed correctly, but parsing of 'meta' failed.
That's narrowing the area of where the bug could be.

I hope this isn't too tiring for you, but I want you to go through another set of instructions:
1. [Download yet another pre-release](https://github.com/Bridel-Igor/Wallomizer/releases/tag/v1.1.0.3) with even more logging enabled.
2. Do steps 2-5 from previous step list.
3. This time in `%AppData%/Roaming/Wallomizer/Logs` you will find 4 `.log` files. Send all of them to me and regenerate API Key if you want.

**Comment by nasyaldnya** [comment]
[Internet_DownloadToBuffer.log](https://github.com/Bridel-Igor/Wallomizer/files/9128584/Internet_DownloadToBuffer.log)
[Internet_m_pBuffer.log](https://github.com/Bridel-Igor/Wallomizer/files/9128585/Internet_m_pBuffer.log)
[Internet_parse.log](https://github.com/Bridel-Igor/Wallomizer/files/9128586/Internet_parse.log)
[SearchCollection_loadSettings.log](https://github.com/Bridel-Igor/Wallomizer/files/9128587/SearchCollection_loadSettings.log)

**Comment by Bridel-Igor** [comment]
Ok. I think I found the root of all problems.
When an app downloads data list from URL it prepares buffer for download. Most of the time it has sufficient size. But in your case it's too small. So the data, that needs to be parsed placed after the end of buffer, and it's never found.
I think your 'items per page' is higher than usual API returns.
Good thing is that I can fix it now. I think update with the fix will be available in 2-3 days. I'll remove all pre-releases. You can use 1.1.0 version without API Key until then.
Thank you for your time contribution!

**Comment by Bridel-Igor** [comment]
It's connected to Wallhaven's Browsing settings - Thumbs Per Page.
You can set it to the value 24. So you can use Wallomizer with API Key until the update.
After update you can return Thumbs Per Page to your original value.

**Comment by nasyaldnya** [comment]
Thank you very much. ❤
